version: '3.7'

services:
  traefik:
    image: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.mysql.address=:3306"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "8081:8080"
      - "3306:3306"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  backend-auth:
    build:
      context: ../../images/auth
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
        spring_profiles_active: docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`localhost`) && PathPrefix(`/api/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"

  backend-app:
    build:
      context: ../../images/app
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
        spring_profiles_active: docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`) && PathPrefix(`/api/app`)"
      - "traefik.http.services.app.loadbalancer.server.port=8080"

  db:
    build: ../../images/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mysql.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mysql.entrypoints=mysql"
      - "traefik.tcp.routers.mysql.service=mysql"
      - "traefik.tcp.services.mysql.loadbalancer.server.port=3306"


