version: '3.7'

services:
  
  payara:
    build: ../../images/payara
    environment:
      PAYARA_ARGS: "--debug"
    ports:
      - 8080:8080
      - 4848:4848
      - 9009:9009
    volumes:
        - "${PWD}/app/target/Project-One.war:/opt/payara/deployments/Project-One.war"
    
  
  db:
    build: ../../images/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
     - 3306:3306
    environment:
      MYSQL_DATABASE: amt
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
